### PR TITLE
Feat(77): Reserve addresses

### LINKED ISSUE #77: [Landing] Implement reserve addresses section
## Description

This issue is to restyle the existing reserve addresses section as well as update where appropriate. 

## Related info

- [Design desktop](https://www.figma.com/design/eW63rQE38ql8NGBYcFnCSJ/Analytics-portal?node-id=6587-2278&m=dev)
- [Design mobile](https://figma.com/design/eW63rQE38ql8NGBYcFnCSJ/Analytics-portal?node-id=6738-1701&m=dev)
- [Existing implementation](https://github.com/mento-protocol/reserve-site/blob/master/src/components/ReserveAddresses.tsx)

### PR DESCRIPTION
**Pull request by RyRy79261**
### Description

This PR implements a raw version of the reserve addresses, in order to maintain uniformity, shortening of the addresses was used.

### Other changes

- Added loading skeleton for reserve composition pie

### Tested

- Checked on mobile and desktop

### Related issues

- Closes #77

### CODE REVIEW

**Review by bayological — COMMENTED** [review]
This title should be outside of the card:
image

Design:
image

**Review by baroooo — DISMISSED** [review]
image

1. Content does not fit on smaller screens
2. NIT, the way we truncate addresses feels weird(15 hex numbers + ... + 15 hex numbers). Truncated addresses are usually much shorter(4hex + ... + 4 hex etc).
3. There is not address truncating on desktop designs, looking at the PR description I guess that was intended but that looks weird to me because there will be huge white space after a shortened address. NIT but I would either use the full addresses on both screen sizes(with a smaller font on mobile), or use the full address on desktop and much shorter address on mobile(4-5hex+..+4-5hex).
image

**Comment by denviljclarke** [comment]
nit: it'd be nice if we could have all the copy icons aligned

**Review by baroooo — COMMENTED** [review]
LGTM apart from what Jamal already pointed out

**Review by philbow61 — APPROVED** [review]
Marvelous 💯 🏅

**Review by nvtaveras — APPROVED** [review]

**Pull request merged**
